version: '3.3'
services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.1
    container_name: es01
    environment:
      discovery.type: single-node
      bootstrap.memory_lock: 'true'
      http.cors.enabled: 'true'
      http.cors.allow-origin: "*"
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"

    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200



  kib01:
    image: docker.elastic.co/kibana/kibana:7.14.1
    container_name: kib01
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://es01:9200
      ELASTICSEARCH_HOSTS: '["http://es01:9200"]'


  apache:
    image: httpd:2.4-alpine
    ports:
      - "8080:80"
    volumes:
      - ./front/:/usr/local/apache2/htdocs/
      - ./config/apache2/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./logs/apache2:/usr/local/apache2/logs

volumes:
  data01:
    driver: local
