version: '2.2'
services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.1
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - cluster.initial_master_nodes=es01,
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - http.cors.enable=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200



  kib01:
    image: docker.elastic.co/kibana/kibana:7.14.1
    container_name: kib01
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://es01:9200
      ELASTICSEARCH_HOSTS: '["http://es01:9200"]'


  logstash:
    image: docker.elastic.co/logstash/logstash:7.14.1
    volumes:
      - ./config/logstash/logstash-apache.conf:/opt/logstash/logstash.conf
      - ./logs:/logs
    links:
      - es01
    command: logstash -f /opt/logstash/logstash.conf

  apache:
    image: httpd:2.4-alpine
    ports:
      - "8080:80"
    volumes:
      - ./front/:/usr/local/apache2/htdocs/
      - ./config/apache2/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./logs/apache2:/usr/local/apache2/logs

volumes:
  data01:
    driver: local
